# Generated by Django 4.1.3 on 2022-12-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Incidences', '0002_alter_waterway_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='road',
            name='name',
            field=models.CharField(max_length=48, null=True),
        ),
    ]
