# Generated by Django 4.1.3 on 2022-12-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Incidences', '0003_alter_road_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='road',
            name='shape_len',
            field=models.FloatField(null=True),
        ),
    ]
