# Generated by Django 4.1.3 on 2022-12-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Incidences', '0005_alter_building_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='type',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
