# Generated by Django 4.1.3 on 2023-04-20 16:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Incidences', '0006_alter_building_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='proad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48, null=True)),
                ('type', models.CharField(max_length=16)),
                ('shape_len', models.FloatField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
            ],
        ),
    ]
