# Generated by Django 4.1.3 on 2023-04-21 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Incidences', '0007_proad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='proad',
        ),
    ]
