# Generated by Django 4.1.3 on 2023-08-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Incidences', '0011_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='lname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
