# Generated by Django 4.1.3 on 2023-11-22 17:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Incidences', '0012_contact_lname'),
    ]

    operations = [
        migrations.CreateModel(
            name='updateroad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('desc', models.TextField()),
            ],
        ),
    ]
