# Generated by Django 4.1.3 on 2023-11-22 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Incidences', '0013_updateroad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Elevation',
        ),
    ]
