# Generated by Django 4.1.3 on 2023-11-22 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Incidences', '0014_delete_elevation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='updateroad',
        ),
    ]
