# Generated by Django 4.1.3 on 2023-11-22 17:47

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Incidences', '0016_updateroad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updateroad',
            name='location',
            field=django.contrib.gis.db.models.fields.MultiPointField(srid=4326),
        ),
    ]
